
package:
    name: malleefowl
    version: 0.1dev

source:
    git_url: git://redmine.dkrz.de/malleefowl.git
    git_tag: pingudev

build:
    number: 2 

requirements:
    build:
        - python
        - setuptools
        - pywps
        - owslib
        - dateutil
        - lxml
        - netcdf4
        - pyyaml
        - yaml
        - pymongo
        - pyopenssl
        - restflow
        - concurrentloghandler
        - ipython
        - nose

    run:
        - python
        - setuptools
        - pywps
        - owslib
        - dateutil
        - lxml
        - netcdf4
        - pyyaml
        - yaml
        - pymongo
        - pyopenssl
        - restflow
        - concurrentloghandler
        - ipython
        - nose

test:
    imports:
        - malleefowl

    #commands:
    #    -

about:
    home: https://mouflon.dkrz.de/help
    license: Apache License v2.0

