
package:
    name: malleefowl
    version: 0.1.3

source:
    git_url: https://github.com/bird-house/malleefowl.git

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - pywps
        - owslib
        - dateutil
        - lxml
        - netcdf4
        - pyyaml
        - yaml
        - pymongo
        - pyopenssl
        - restflow
        - concurrentloghandler

    run:
        - python
        - setuptools
        - pywps
        - owslib
        - dateutil
        - lxml
        - netcdf4
        - pyyaml
        - yaml
        - pymongo
        - pyopenssl
        - restflow
        - concurrentloghandler

test:
    imports:
        - malleefowl

    #commands:
    #    -

about:
    home: https://mouflon.dkrz.de/help
    license: Apache License v2.0

