package:
  name: pydap
  version: !!str 3.1.1

source:
  fn: Pydap-3.1.1.tar.gz
  url: https://pypi.python.org/packages/source/P/Pydap/Pydap-3.1.1.tar.gz
  md5: d13630328c121eeeb0e0f015eb9e7124
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pydap = pydap:main
    #
    # Would create an entry point called pydap that calls pydap.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy
    - httplib2
    - genshi
    - paste
    - pastescript
    - pastedeploy
    - coards
    - m2crypto


test:
  # Python imports
  imports:
    - paste
    - paste.deploy
    - pydap

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pythonpaste.org/deploy/
  license: MIT License
  summary: 'Load, configure, and compose WSGI applications and servers'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
