package:
    name: gdal-data
    version: 1.11.1

source:
  fn: gdal-1.11.1.tar.gz
  url: http://download.osgeo.org/gdal/1.11.1/gdal-1.11.1.tar.gz
  md5: 7555f55855f613be49e6508eed0ac3fa

build:
    number: 0

requirements:
    run:
        - gdal

about:
    home: http://www.gdal.org/
    license: MIT
    summary: Data removed from the gdal package.
