package:
  name: python-swiftclient
  version: !!str 1.8.0

source:
  fn: python-swiftclient-1.8.0.tar.gz
  url: https://pypi.python.org/packages/source/p/python-swiftclient/python-swiftclient-1.8.0.tar.gz
  md5: 1f7be5a72f3590d20cf2706d86486927
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-swiftclient = python-swiftclient:main
    #
    # Would create an entry point called python-swiftclient that calls python-swiftclient.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  # imports:

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.openstack.org/
  license:  Apache Software License
  summary: 'OpenStack Object Storage API Client Library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
