
package:
    name: pycsw
    version: 1.8.3

source:
    #git_url: https://github.com/geopython/pycsw.git
    #git_tag: master

    fn: pycsw-1.8.3.tar.gz
    url: https://pypi.python.org/packages/source/p/pycsw/pycsw-1.8.3.tar.gz
    md5: 1bcc72a0ad8104e5836f9c48bffd287a

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - psycopg2
        - sqlalchemy
        - geolinks
        - lxml
        - owslib
        - pyproj
        - shapely
    run:
        - python
        - psycopg2
        - sqlalchemy
        - geolinks
        - lxml
        - owslib
        - pyproj
        - shapely

test:
    imports:
        - pycsw

    #commands:
    #    -

about:
    home: http://pycsw.org/
    license: MIT

