
package:
    name: birdhousebuilder.recipe.supervisor
    version: 0.0.3

source:
    fn: birdhousebuilder.recipe.supervisor-0.0.3.tar.gz
    url: https://testpypi.python.org/packages/source/b/birdhousebuilder.recipe.supervisor/birdhousebuilder.recipe.supervisor-0.0.3.tar.gz
    md5: 3b8af86099ab56ef107d6201ac5f1bf7 

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - zc.buildout
        - mako
        - birdhousebuilder.recipe.conda
    run:
        - python
        - setuptools
        - zc.buildout
        - mako
        - birdhousebuilder.recipe.conda

test:
    imports:
        - birdhousebuilder.recipe.supervisor

    #commands:
    #    -

about:
    home: https://mouflon.dkrz.de/help
    license: Apache License v2.0

