
package:
    name: concurrentloghandler
    version: 0.9.1

source:
    fn: ConcurrentLogHandler-0.9.1.tar.gz
    url: https://pypi.python.org/packages/source/C/ConcurrentLogHandler/ConcurrentLogHandler-0.9.1.tar.gz
    md5: 9609ecc4c269ac43f0837d89f12554c3

build:
    number: 0

requirements:
    build:
        - python
        - setuptools

    run:
        - python

test:
    imports:
        - cloghandler

    #commands:
    #    -

about:
    home: http://launchpad.net/python-concurrent-log-handler
    license: Apache License v2.0

