package:
    name: ocgis
    version: 0.08b

source:
    git_url: https://github.com/NCPP/ocgis.git
    git_tag: next

build:
    number: 4

requirements:
    build:
        - python
        - setuptools
        - numpy
        - netcdf4
        - shapely
        - fiona
        - gdal
        - gdal-data
        - icclim

    run:
        - python
        - numpy
        - netcdf4
        - shapely
        - fiona
        - gdal
        - gdal-data
        - icclim

test:
    # export GDAL_DATA=${prefix}/share/gdal
    imports:
        - ocgis

    #commands:
    #    -

about:
    home: http://ncpp.github.io/ocgis/install.html#installing-openclimategis
    license: NCSA License

