
package:
    name: nginx
    version: 1.6.0

source:
    fn: nginx-1.6.0.tar.gz
    url: http://nginx.org/download/nginx-1.6.0.tar.gz
    md5: 8efa354f1c3c2ccf434a50d3fbe82340

build:
    number: 0

requirements:
    build:
        - pcre
        - openssl
        - zlib

    run:
        - pcre 
        - openssl
        - zlib

test:
    #imports:
    #    - nginx

    #commands:
    #    -

about:
    home: http://www.nginx.org
    license: 2-clause BSD-like license

