
package:
    name: nginx
    version: 1.4.6

source:
    fn: nginx-1.4.6.tar.gz
    url: http://nginx.org/download/nginx-1.4.6.tar.gz
    #md5:

build:
    number: 0

requirements:
    build:
        - pcre
        - openssl
        - zlib

    run:
        - pcre 
        - openssl
        - zlib

test:
    #imports:
    #    - nginx

    #commands:
    #    -

about:
    home: http://www.nginx.org
    license: 2-clause BSD-like license

