
package:
    name: nginx
    version: 1.6.2

source:
    fn: nginx-1.6.2.tar.gz
    url: http://nginx.org/download/nginx-1.6.2.tar.gz
    md5: d1b55031ae6e4bce37f8776b94d8b930

build:
    number: 3

requirements:
    build:
        - pcre
        - openssl
        - zlib
        - pcre

    run:
        - pcre 
        - openssl
        - zlib
        - pcre 

about:
    home: http://www.nginx.org
    license: 2-clause BSD-like license

