package:
  name: phantomjs
  version: 1.9.7

source:
  fn: phantomjs-1.9.7-windows.zip [win]
  url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-windows.zip [win]
  fn: phantomjs-1.9.7-macosx.zip [osx]
  url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-macosx.zip [osx]

build:
  number: 0

about:
  home: http://phantomjs.org/
  license: BSD

# vim:set ts=8 sw=2 sts=2 tw=78 et:
