package:
  name: pywget
  version: !!str 2.2

source:
  fn: wget-2.2.tar.gz
  url: https://pypi.python.org/packages/source/w/wget/wget-2.2.tar.gz
  md5: 1ffdf1a214aa0d30edb0fc8b2a628738
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - wget = wget:main
    #
    # Would create an entry point called wget that calls wget.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - wget

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/techtonik/python-wget/
  license: Public Domain
  summary: 'pure python download utility'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
