package:
  name: cdo
  version: 1.6.4

source:
  fn: cdo-1.6.4.tar.gz
  url: https://code.zmaw.de/attachments/download/8376/cdo-1.6.4.tar.gz
  md5: a23d1b6f0708d3a510be6ede6ef4b5b9

build:
  number: 3 

requirements:
  build:
    - jasper
    - grib_api
    - libnetcdf
    - proj4
  run:
    - jasper
    - grib_api
    - libnetcdf
    - proj4

test:
  commands:
    # DYLD_LIBRARY_PATH=/Users/pingu/anaconda/lib
    - cdo -h

about:
  home: https://code.zmaw.de/projects/cdo
  license: GNU General Public License v2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
