package:
  name: cdo
  version: 1.6.2

source:
  fn: cdo-1.6.2.tar.gz
  url: https://code.zmaw.de/attachments/download/6764/cdo-1.6.2.tar.gz
  md5: a17b23e09a2cae95504bfb2a4338e632

build:
  number: 2            [linux]

requirements:
  build:
    - jasper
    - grib_api
    - libnetcdf
    - proj4
  run:
    - jasper
    - grib_api
    - libnetcdf
    - proj4

test:
  commands:
    - cdo -h

about:
  home: https://code.zmaw.de/projects/cdo
  license: GNU General Public License v2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
