
package:
    name: birdhousebuilder.recipe.conda
    version: 0.0.2

source:
    fn: birdhousebuilder.recipe.conda-0.0.2.tar.gz
    url: https://testpypi.python.org/packages/source/b/birdhousebuilder.recipe.conda/birdhousebuilder.recipe.conda-0.0.2.tar.gz
    md5: ad690de62209b085a1d9570726b694c5

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - zc.buildout
    run:
        - python
        - setuptools
        - zc.buildout

test:
    imports:
        - birdhousebuilder.recipe.conda

    #commands:
    #    -

about:
    home: https://mouflon.dkrz.de/help
    license: Apache License v2.0

