
package:
    name: owslib
    version: 0.8dev

source:
    git_url: https://github.com/geopython/OWSLib.git
    git_tag: master

    #fn: OWSLib-0.8.8.tar.gz
    #url: https://pypi.python.org/packages/source/O/OWSLib/OWSLib-0.8.8.tar.gz
    #md5: 09c74461605f18d0381080ab0ecb20cd

build:
    number: 2

requirements:
    build:
        - python
        - setuptools
        - pytz
        - dateutil
        - lxml

    run:
        - python
        - pytz
        - dateutil
        - lxml

test:
    imports:
        - owslib

    #commands:
    #    -

about:
    home: http://geopython.github.io/OWSLib/
    license: BSD

