
package:
    name: lapis
    version: 0.2dev

source:
    git_url: https://github.com/TobiasWeigel/lapis.git
    git_tag: master


build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - simplejson

    run:
        - python
        - simplejson

test:
    imports:
        - lapis

    #commands:
    #    -

about:
    home: https://github.com/TobiasWeigel/lapis
    license: Copyright DKRZ

