package:
  name: pysftp
  version: !!str 0.2.8

source:
  fn: pysftp-0.2.8.tar.gz
  url: https://pypi.python.org/packages/source/p/pysftp/pysftp-0.2.8.tar.gz
  md5: 10bd5452aee5684871f434f5cfc8e07b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysftp = pysftp:main
    #
    # Would create an entry point called pysftp that calls pysftp.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - paramiko >=1.7.7

  run:
    - python
    - paramiko >=1.7.7

test:
  # Python imports
  imports:
    - pysftp

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/dundeemt/pysftp
  license:  BSD License
  summary: 'A friendly face on SFTP'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
