package:
  name: pydap.responses.netcdf
  version: !!str 0.1.4.1

source:
  fn: pydap.responses.netcdf-0.1.4.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pydap.responses.netcdf/pydap.responses.netcdf-0.1.4.1.tar.gz
  md5: d37e200302f1f14382f4b86a034b4620
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pydap.responses.netcdf = pydap.responses.netcdf:main
    #
    # Would create an entry point called pydap.responses.netcdf that calls pydap.responses.netcdf.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - pydap
    - pupynere

test:
  # Python imports
  imports:
   - pydap

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/robertodealmeida/pupynere/
  license: MIT License
  summary: 'NetCDF file reader and writer.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
