package:
  name: gdal
  version: 1.11.0

source:
  fn: gdal-1.11.0.tar.gz
  url: http://download.osgeo.org/gdal/1.11.0/gdal-1.11.0.tar.gz
  md5: 9fdf0f2371a3e9863d83e69951c71ec4

build:
    number: 0

requirements:
  build:
    - python
    - libnetcdf
    - proj4
  run:
    - python
    - libnetcdf
    - proj4

test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo

about:
  home: http://www.gdal.org/
  license: MIT
