package:
  name: proj4
  version: 4.8.0

source:
  fn: proj-4.8.0.tar.gz
  url: http://download.osgeo.org/proj/proj-4.8.0.tar.gz
  md5: d815838c92a29179298c126effbb1537

build:
  number: 1            [linux]

about:
  home: http://trac.osgeo.org/proj/
  license: MIT-license (http://trac.osgeo.org/proj/wiki/WikiStart#License)
