package:
  name: pastescript
  version: !!str 1.7.5

source:
  fn: PasteScript-1.7.5.tar.gz
  url: https://pypi.python.org/packages/source/P/PasteScript/PasteScript-1.7.5.tar.gz
  md5: 4c72d78dcb6bb993f30536842c16af4d
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pastescript = pastescript:main
    #
    # Would create an entry point called pastescript that calls pastescript.main()

    - paster=paste.script.command:run

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - paste >=1.3
    - pastedeploy

  run:
    - python
    - setuptools
    - paste >=1.3
    - pastedeploy

test:
  # Python imports
  imports:
    - paste
    - paste.script
    - paste.script.util

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - paster --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pythonpaste.org/script/
  license: MIT License
  summary: 'A pluggable command-line frontend, including commands to setup package file layouts'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
