package:
  name: pydap.responses.wms
  version: !!str 0.5.4

source:
  fn: pydap.responses.wms-0.5.4.tar.gz
  url: https://pypi.python.org/packages/source/p/pydap.responses.wms/pydap.responses.wms-0.5.4.tar.gz
  md5: 9093ff2f5e9fcc61dda5dadd150d9011
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pydap.responses.wms = pydap.responses.wms:main
    #
    # Would create an entry point called pydap.responses.wms that calls pydap.responses.wms.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pydap
    - paste
    - matplotlib
    - coards
    - iso8601

test:
  # Python imports
  imports:
    - pydap
    - iso8601

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/micktwomey/pyiso8601
  license: MIT License
  summary: 'Simple module to parse ISO 8601 dates'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
