package:
  name: r
  version: 3.1.0

source:
  fn: R-3.1.0.tar.gz
  url: http://cran.rstudio.com/src/base/R-3/R-3.1.0.tar.gz

build:
  number: 2 

build:
  rpaths:
    - lib/R/lib/
    - lib/
  number: 2 # [linux]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - readline  # [not win]
    - ncurses   # [not win]
    - tk        # [not win]
    - zlib      # [not win]
    - gsl       # [not win]
    - cairo     # [linux]
    - pango     # [linux]
    - jpeg      # [not win]
    - libpng    # [not win]
    - libtiff   # [not win]
    - libxml2 # Not really sure if libxml2 is needed [not win]
    - gcc       # [not win]
    - pcre      # [not win]

    - mingw     # [win]

  run:
    - readline  # [not win]
    - ncurses   # [not win]
    - tk        # [not win]
    - zlib      # [not win]
    - cairo     # [linux]
    - pango     # [linux]
    - jpeg      # [not win]
    - libpng    # [not win]
    - libtiff   # [not win]
    - libxml2   # [not win]
    - gcc       # [not win]
    - pcre      # [not win]

test:
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e  "cat('ok')"

about:
  home: http://www.r-project.org/
  license: GPL
