package:
  name: r
  version: 3.1.0

source:
  fn: R-3.1.0.tar.gz
  url: http://cran.rstudio.com/src/base/R-3/R-3.1.0.tar.gz

build:
  number: 2 

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - readline
    - tk
    - zlib
    - gmp
    - gsl
    - cairo     [linux]
    - freeglut  [linux]
    - freetype
    - jpeg
    - libpng
    - libtiff
    - libxml2
    - libxslt
    - gcc

  run:
    - readline
    - tk
    - zlib
    - gmp
    - gsl
    - cairo     [linux]
    - freeglut  [linux]
    - freetype
    - jpeg
    - libpng
    - libtiff
    - libxml2
    - libxslt
    - gcc

test:
  commands:
    - R -h
    - R --version
    - Rscript --version

about:
  home: http://www.r-project.org/
  license: GPL
